apply plugin: 'groovy'

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.4.15'
    testCompile group: 'org.apache.commons', name: 'commons-lang3', version: '3.7'
    testCompile 'org.slf4j:slf4j-api:1.6.1'
    testCompile 'ch.qos.logback:logback-classic:1.2.3'
    testCompile 'junit:junit:4.12'
    testCompile 'io.github.http-builder-ng:http-builder-ng-apache:1.0.3'
}

